### PR TITLE
Implement exporting all results, with one file per variable

### PR DESCRIPTION
**Pull request by mseaborn**
This outputs one *.tab table file for each variable in the Pyomo model.

I tested this manually by running all of the examples.

Josiah, this is the change that we pair-programmed last year.  After this is committed, I'll turn the examples into automated tests where the output is checked.

### CODE REVIEW

**Comment by josiahjohnston** [comment]
I got the following error on my machine which went away after I updated Pyomo from v 4.0.x to 4.2.x. 

```shell
siah-macbookpro:~ josiah$ cd /Users/josiah/src/switch-mseaborn/examples/3zone_toy/
siah-macbookpro:3zone_toy josiah$ export PYTHONPATH=/Users/josiah/src/switch-mseaborn
siah-macbookpro:3zone_toy josiah$ ../../switch_mod/
project/  test_dat/ 
siah-macbookpro:3zone_toy josiah$ python ../../switch_mod/solve.py 
Traceback (most recent call last):
  File "../../switch_mod/solve.py", line 57, in <module>
    main(sys.argv[1:])
  File "../../switch_mod/solve.py", line 37, in main
    switch_model.save_results(results, switch_instance, args.outputs_dir)
  File "/Users/josiah/src/switch-mseaborn/switch_mod/utilities.py", line 202, in save_results
    _save_generic_results(instance, outdir)
  File "/Users/josiah/src/switch-mseaborn/switch_mod/utilities.py", line 470, in _save_generic_results
    for var in instance.component_objects():
AttributeError: 'AbstractModel' object has no attribute 'component_objects'
siah-macbookpro:3zone_toy josiah$ pyomo --version
Pyomo 4.0.9682 (CPython 2.7.9 on Darwin 13.4.0)
siah-macbookpro:3zone_toy josiah$ sudo pip install --upgrade pyomo
    ...
siah-macbookpro:3zone_toy josiah$ pyomo --version
Pyomo 4.2.10784 (CPython 2.7.9 on Darwin 13.4.0)
```

**Comment by josiahjohnston** [comment]
Can you please merge this pull request in?
